<a href="https://colab.research.google.com/github/2303A51256/AIML/blob/main/lab1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
l = []
n = int(input("Enter No.of elements in a list : "))
while (n>0):
  e = int(input("Enter element : "))
  l.append(e)
  n-=1
print(l)
arr1 = np.array(l)
print(type(l))
print(arr1)
print(type(arr1))
m = []
n = int(input("Enter No.of elements in a list : "))
while (n>0):
  e = int(input("Enter element : "))
  m.append(e)
  n-=1
print(m)
arr2 = np.array(m)
print(type(m))
print(arr2)
print(type(arr2))
print("Multiplication : ",arr1*arr2)
print("Division : ",arr1/arr2)
print("Exponent : ",arr1**arr2)
print("Addition : ",arr1+arr2)
p = np.sin(arr1)
q = np.log(arr1)
r = np.log2(arr2)
s = np.exp(arr1)
print(p)
print(q)
print(r)
print(s)
st1 = "Vineeth"
st2 = " Puneriya"
print(st1+st2)




Enter No.of elements in a list : 3
Enter element : 1
Enter element : 6
Enter element : 7
[1, 6, 7]
<class 'list'>
[1 6 7]
<class 'numpy.ndarray'>
Enter No.of elements in a list : 3
Enter element : 3
Enter element : 4
Enter element : 9
[3, 4, 9]
<class 'list'>
[3 4 9]
<class 'numpy.ndarray'>
Multiplication :  [ 3 24 63]
Division :  [0.33333333 1.5        0.77777778]
Exponent :  [       1     1296 40353607]
Addition :  [ 4 10 16]
[ 0.84147098 -0.2794155   0.6569866 ]
[0.         1.79175947 1.94591015]
[1.5849625 2.        3.169925 ]
[   2.71828183  403.42879349 1096.63315843]
Vineeth Puneriya
